# quotes.py
# Original quotes written for this bot -- free to use, no API cost, no copyright risk.
# Add more anytime: just append a string to the right list.

MOTIVATIONAL = [
    "The comeback is always stronger than the setback.",
    "Small steps every day still get you there.",
    "Your only competition is who you were yesterday.",
    "Discipline is choosing what you want most over what you want now.",
    "Storms don't last. Neither does your struggle.",
    "You don't need to see the whole staircase, just take the first step.",
    "Tired is not the same as done.",
    "Every expert was once a beginner who refused to quit.",
    "Progress is still progress, no matter how slow.",
    "The pain you feel today is the strength you feel tomorrow.",
    "Bet on yourself. The odds are better than you think.",
    "Hard days build the people who go on to do great things.",
    "You are one decision away from a completely different life.",
    "Consistency beats motivation every single time.",
    "Nobody is coming to save you. Good. Save yourself.",
    "Doubt kills more dreams than failure ever will.",
    "Start where you are. Use what you have. Do what you can.",
    "The version of you that you're becoming is worth the wait.",
    "Success is built in the hours no one is watching.",
    "You didn't come this far to only come this far.",
]

LOVE_EMOTIONAL = [
    "Some people don't need words to feel like home.",
    "Loving you never felt like a choice, it felt like breathing.",
    "The best love doesn't complete you, it grows with you.",
    "I fall for you a little more in every ordinary moment.",
    "Distance means nothing when someone means everything.",
    "You are my favorite notification.",
    "Real love is quiet, steady, and never runs out of patience.",
    "I didn't need saving, I just needed someone who stayed.",
    "The heart remembers what the mind tries to forget.",
    "Some connections are just written in the stars.",
    "You held my heart before you even knew its weight.",
    "Even silence feels good when I'm with you.",
    "Healing looks like choosing peace over people who hurt you.",
    "I love you in the quiet, unglamorous, everyday way.",
    "Your presence is the calm after every storm in my life.",
    "Some souls just recognize each other, no explanation needed.",
    "Missing someone is just love with nowhere to go.",
    "You are the softest place I have ever landed.",
    "True love doesn't ask you to shrink to fit in.",
    "Being chosen every day is better than any grand gesture.",
]

MOTIVATIONAL_HINDI = [
    "हार मत मानो, मंज़िल दूर नहीं है।",
    "मेहनत करने वालों की कभी हार नहीं होती।",
    "आज का दर्द कल की ताकत बनेगा।",
    "खुद पर भरोसा रखो, बाकी सब हो जाएगा।",
    "रास्ता मुश्किल है इसलिए मंज़िल खूबसूरत है।",
    "छोटी शुरुआत से बड़े सपने पूरे होते हैं।",
    "जो रुकते नहीं, वही जीतते हैं।",
    "हर सुबह एक नया मौका लेकर आती है।",
    "गिरना बुरा नहीं, ना उठना बुरा है।",
    "सपने वो नहीं जो सोते वक़्त आएं, सपने वो हैं जो सोने ना दें।",
    "कोशिश करने वालों की कभी हार नहीं होती।",
    "खुद को साबित करने के लिए किसी और की ज़रूरत नहीं।",
    "वक़्त बदलता है, बस डटे रहो।",
    "हर मुश्किल के बाद एक आसानी है।",
    "जीत उन्हीं की होती है जो हार कर भी लड़ते रहें।",
    "मंज़िल मिल ही जाएगी, भटकते ही सही, राह चलते तो हैं।",
    "खुद पर यकीन रखो, दुनिया अपने आप साथ देगी।",
    "आज जो बोया है, वही कल काटोगे।",
    "थक कर बैठना नहीं, थक कर आगे बढ़ना है।",
    "सफलता उनकी होती है जो कोशिश करना नहीं छोड़ते।",
]

LOVE_EMOTIONAL_HINDI = [
    "तेरी यादें ही अब मेरी सबसे प्यारी सहेली हैं।",
    "तुझसे मिलकर लगा जैसे घर मिल गया।",
    "कुछ रिश्ते बिना कहे भी समझ आ जाते हैं।",
    "तेरे बिना हर जगह अधूरी सी लगती है।",
    "तेरी मुस्कान ही मेरी सबसे बड़ी खुशी है।",
    "दूरियां कुछ नहीं होतीं जब दिल पास हो।",
    "तुझे सोचना भी अब आदत बन गई है।",
    "प्यार में शब्दों की नहीं, एहसास की ज़रूरत होती है।",
    "तू है तो हर मुश्किल आसान लगती है।",
    "कुछ लोग बिना कुछ कहे भी सुकून दे जाते हैं।",
    "तेरी बातें अब भी वैसे ही याद हैं।",
    "इश्क़ में सब्र सबसे बड़ी ताकत है।",
    "तुझसे दूर रहकर भी तू हमेशा पास लगता है।",
    "कुछ मोहब्बतें वक़्त के साथ और गहरी हो जाती हैं।",
    "तेरा साथ ही अब मेरी सबसे बड़ी दौलत है।",
]

CATEGORIES = {
    "motivational": {"label": "Motivational / Success", "lang": "en", "quotes": MOTIVATIONAL, "photo_keywords": ["sunrise mountain", "runner sunset", "open road", "city skyline dawn"]},
    "love": {"label": "Love / Emotional", "lang": "en", "quotes": LOVE_EMOTIONAL, "photo_keywords": ["soft sunset sky", "rain window", "autumn leaves path", "candle warm light"]},
    "hindi_motivational": {"label": "हिंदी: मोटिवेशनल", "lang": "hi", "quotes": MOTIVATIONAL_HINDI, "photo_keywords": ["sunrise mountain", "runner sunset", "open road", "city skyline dawn"]},
    "hindi_love": {"label": "हिंदी: प्रेम / भावनिक", "lang": "hi", "quotes": LOVE_EMOTIONAL_HINDI, "photo_keywords": ["soft sunset sky", "rain window", "autumn leaves path", "candle warm light"]},
}
